### ISSUE TITLE
Issue while parsing some chinese character

### ISSUE THREAD

**Issue by Adavo** [rickyah/ini-parser#102]
Hello,

I found an issue when I try to parse a section that contains this Chinese character : "…"
I assume that key/value parsing should have the same issue too.

Here is the error log:
Unknown file format. Couldn't parse the line: '[HSK2.Grammar.Complex sentence with 虽然…但是… ]'. while parsing line number 0 with value '' - IniParser version: 2.2.4.0 while parsing line number 1 with value '[HSK2.Grammar.Complex sentence with 虽然…但是… ]' - IniParser version: 2.2.4.0

I checked my file, it's encoded into UTF8 With BOM.
Thanks

**Comment by rickyah** [comment]
@Adavo could you attach an ini file that allows me to reproduce this error?

**Comment by Adavo** [comment]
Here is the file: 
[grammar.txt](https://github.com/rickyah/ini-parser/files/163058/grammar.txt)
Thanks !

**Comment by Adavo** [comment]
I clone the repos and try to execute. The issue seams to be localized into the regex (Configuration.SectionRegex) that not match due to the special character. The regex is:
{^(\s*?)\[{1}\s*[_\"\'\{\}\#\+\;\*\%\(\)\=\?\&\$\,\:\/\.\-\w\d\s\\\~]+\s*](\s*?)$}

I added just the special character to this regex:
{^(\s*?)\[{1}\s*[_\"\'\{\}\#\+\…\;\*\%\(\)\=\?\&\$\,\:\/\.\-\w\d\s\\\~]+\s*](\s*?)$}

I have to assume that maybe this regex can be "easier" ? I mean look at any character until the ] ? Or do you have a good reason to test specific character like that ? I assume that this "hotfix" is ok but this parser should have issue later on another special character that we don't escape, isnt' it ?

**Comment by rickyah** [comment]
Hi @Adavo 

I've made some research, and using the regex 
`{1}\s*[\p{L}\p{P}\p{M}\p{N}_\""\'\{\}\#\+\;\*\%\(\)\=\?\&\$\,\:\/\.\-\w\d\s\\\~]+\s*`
makes everything work. 
This new regex should work for any unicode:

- letter (`\p{L}`)
- punctuation (`\p{P}`)
- diacritic mark (`\p{M}`) 
- or number (`\p{N}`)  

This works for the special character you had problem with (…) and should potentially work for any other special character.

The only caveat is that you must define the UTF8 encoding if you want to write a file correctly (see example code below)

I've just added this test to check for unicode characters and using the file you attached. 
**Is it ok if I put the file you attached publicly in the repository?** Does it contain any kind of sensible information? I can't read chinese, so I can't tell. If you are ok with this I'll merge my local branch and upload it to the repository.


This is the test I've added to the suite in the project

```csharp
        [Test, Description("Check unicode characters")]
        public void check_parse_unicode_chinese_characters()
        {
            var parser = new FileIniDataParser();
            parser.Parser.Configuration.ThrowExceptionsOnError = true;

            var iniFileData = parser.ReadFile("unicode_chinese.ini");

            // If you want to write the file you must specify the encoding
            //parser.WriteFile("unicode_chinese_copy.ini", iniFileData, Encoding.UTF8);

        }
    }
````

**Comment by Adavo** [comment]
Hello and thanks for your answer. Yes you can use my text file as a test it's ok.
Glad to hear that you found a way to fix it and also may fix it for every Unicode character. I used a modified version of your libs for now but if later someone use your library for some Chinese he will be glad to don't have the same bugs. Thanks again.
Sent from my Superphone
Mar 16, 2016 5:38 AM wrote on Ricardo Amores Hernández <notifications@github.com>:
Hi @Adavo

I've made some research, and using the regex
`{1}\s*[\p{L}\p{P}\p{M}\p{N}_\""\'\{\}\#\+\;\*\%\(\)\=\?\&\$\,\:\/\.\-\w\d\s\\\~]+\s*`
makes everything work.
This new regex should work for any unicode:

- letter (`\p{L}`)
- punctuation (`\p{P}`)
- diacritic mark (`\p{M}`)
- or number (`\p{N}`)

This works for the special character you had problem with (…) and should potentially work for any other special character.

The only caveat is that you must define the UTF8 encoding if you want to write a file correctly (see example code below)

I've just added this test to check for unicode characters and using the file you attached.
**Is it ok if I put the file you attached publicly in the repository?** Does it contain any kind of sensible information? I can't read chinese, so I can't tell. If you are ok with this I'll merge my local branch and upload it to the repository.


This is the test I've added to the suite in the project

```csharp
        [Test, Description("Check unicode characters")]
        public void check_parse_unicode_chinese_characters()
        {
            var parser = new FileIniDataParser();
            parser.Parser.Configuration.ThrowExceptionsOnError = true;

            var iniFileData = parser.ReadFile("unicode_chinese.ini");

            // If you want to write the file you must specify the encoding
            //parser.WriteFile("unicode_chinese_copy.ini", iniFileData, Encoding.UTF8);

        }
    }
````


---

**Comment by apalomba** [comment]
Hello there, I seem to be encountering the same problem. I have an INI file that loads okay when running as an application. But when I run my app as a service, ini-parser can not parse the same INI file. I get the following error....

IniParser.Exceptions.ParsingException[br]Could not parse file DataParserSystem.ini while parsing line number 0 with value '' - IniParser version: 2.4.0.0[br]   at IniParser.FileIniDataParser.ReadFile(String filePath, Encoding fileEncoding)

I am specifying Encoding.UTF8. Why would there be a difference in reading the file as a service?


Thanks,
Anthony
