### ISSUE TITLE
Trailing comments not working

### ISSUE THREAD

**Issue by tvanassche** [rickyah/ini-parser#104]
Small fix for the trailing comments on sections not being written to the ini file.

[SectionData.zip](https://github.com/rickyah/ini-parser/files/167674/SectionData.zip)

**Comment by rickyah** [comment]
Sorry, changes you made on the file still won't get persisted to the ini file. And I'm rethinking how to deal with comments without changing its order in the file anyway

**Comment by tvanassche** [comment]
Haven't tested if they get persisted, but with the changes the trailing
comments are actually written to the file (when creating a new file).
