### ISSUE TITLE
Would like to retrieve value of key without knowing section

### ISSUE THREAD

**Issue by njtaz76** [rickyah/ini-parser#106]
Hi, is it possible for you to add the ability to retrieve the value of a key without knowing the section name?  I attempted to use the .GetKey method, but that only works on files that have no sections.  I also attempted Global.GetKeyData but will also not work.

Thank you!!  and thank you for such an awesome component!

**Comment by Svetomech** [comment]
> but that only works on files that have no sections

This sounds very reasonable to me since if a file has sections then values in them might have the same name. Thus, you have to specify section name explicitly. IMHO.

**Comment by njtaz76** [comment]
And if there are duplicates, it could follow the flags related to
duplicates.  Thank you for your quick reply!

**Comment by Svetomech** [comment]
What do you mean by "flags related to duplicates"? 
And I'm not the author, by the way. @rickyah is.

**Comment by njtaz76** [comment]
Oh sorry. Couldn't tell via the email.

**Comment by rickyah** [comment]
You can easily search for keys in the sections:

```csharp
var iniFile = new IniData();

iniFile.Global["key1"] = "value1";
iniFile.Sections.AddSection("sec1");
iniFile.Sections.AddSection("sec2");

iniFile.Sections["sec1"].AddKey("key1", "value2");
iniFile.Sections["sec2"].AddKey("key1", "value3");
int i = 0;

// Do no forget to search in the global section
var keys = new System.Collections.Generic.List<KeyData>();

// Search for the key in all sections of the file sections
keys.Add(iniFile.Global.GetKeyData("key1"));

// This is a test; if the key is not found, a null value will be inserted 
keys.Add(iniFile.Global.GetKeyData("key2"));

foreach (var section in iniFile.Sections)
{
    keys.Add(section.Keys.GetKeyData("key1"));
}

// Remove all null values inserted if you did not found the key
// of course you can check for null values before inserting, but that involves more code 
// and I'm feel lazy :D
keys.RemoveAll( k => k == null);
```
