### ISSUE TITLE
Delete Section

### ISSUE THREAD

**Issue by corystein** [rickyah/ini-parser#107]
The below does not remove the section header.

data[Section].RemoveAllKeys();

**Comment by rexwhitten** [comment]
It seems to me the behavior of RemoveAllKeys should not remove the section, (and thus remove the section header)

**Comment by corystein** [comment]
Is there a way to easily remove the entire section?

Best Regards,
Cory

**Comment by rickyah** [comment]
`iniFile.Sections.RemoveSection("sectionName")`

**Comment by corystein** [comment]
Thank you that’s exactly what I needed.

Best Regards,
Cory

**Comment by rickyah** [comment]
Anytime!
