### ISSUE TITLE
Support of custom line endings (\r\n,\n)

### ISSUE THREAD

**Issue by sergiorykov** [rickyah/ini-parser#108]
I use parser to patch unix ini files with \n line endings on Windows. 
Yes, it's pretty cruel.

Please, consider adding to `IniParserConfiguration ` new option **NewLine** with default `Environment.NewLine`
I can override `IIniDataFormatter `but it's a bit complicated to support all the options.
I thing for `DefaultIniDataFormatter `it's a good extension without loss compability. It internally uses `StringBuilder.AppendLine`.

If you don't mind I can submit pullrequest where I will replace 
`sb.AppendLine(message)` for
```
void AppendLine(StringBuilder sb, message)
{ 
sb.Append(message);
sb.Append(this.Configuration.NewLine);
}
```

**Comment by rickyah** [comment]
Please @sergiorykov  take a look at PR #109 and tell me if you see anything else.

**Comment by sergiorykov** [comment]
It looks like everything is fine!

Thank you :)
