### ISSUE TITLE
_strRegexSpecialChars doesn't contain `]`

### ISSUE THREAD

**Issue by facelesspanda** [rickyah/ini-parser#113]
Can't escape `]` in a configuration string if it's not there. And since the variable is constant, can't add it ourselves.

EDIT: In `IniParserConfiguration`

**Comment by rickyah** [comment]
I don't fully understand what are you trying to accomplish.
Which variable from `IniParserConfiguration`are you referring to? 
Why do you need to escape that particular character, what's the context?

**Comment by facelesspanda** [comment]
It's the field `_strRegexSpecialChars` which lists all the characters that mean something in a regex.

I needed it because I was extending IniParserConfiguration and building a regex, in which I needed to escape the `]` character along with all characters that would be interpreted by the Regex as part of its structure and not a character I wanted to match. I thought about doing a list myself, but I found `_strRegexSpecialChars`, turned out it was incomplete.

**Comment by rickyah** [comment]
Sorry but I still don't know what are you talking about: I can't find the _strRegexSpecialChars field you keep referring to in the codebase.

**Comment by facelesspanda** [comment]
You had me doubting if I didn't mix up this repo with another, but I went digging again and found it:
[This exact line](https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/Model/Configuration/IniParserConfiguration.cs#L282).

**Comment by rickyah** [comment]
Well damn me, it was `_strSpecialRegexChars`, not `_strRegexSpecialChars`. I though we had found a simultaneous bug in Rider, grep and ack! 😆

I'll add the `]` in no time

**Comment by rickyah** [comment]
You got the fix in the developement branch @facelesspanda, thanks!

**Comment by facelesspanda** [comment]
I'll be damned! My bad!
Thanks for the fix though :smile:
