### ISSUE TITLE
ini-parser test

### ISSUE THREAD

**Issue by quicktrick** [rickyah/ini-parser#114]
Hi Ricky!

I wrote a small test of your parser allowing to read all the ini file keys automatically, basing on the correspondent settings class member's definitions.

Please have a look at it: https://bitbucket.org/quicktrick/test-ini-parser.git

May it be useful to include this link in your wiki ?

Best regards!

Alex

**Comment by rickyah** [comment]
Sorry but I fail to see the utility of this test. You seem to have defined a data structure replicating the structure of an INI file and populating that with data read from the IniData parsed using this libraryto check if everything is properly initialized.
This is something specific to the final application using the ini parser, not the parser library itself so it doesn't belong here.
