### ISSUE TITLE
How can i read a mix ini file?

### ISSUE THREAD

**Issue by cp1319421** [rickyah/ini-parser#117]
How can i use the ini-parser read a mix ini file like below? I want get the BoardSN value.

MEAS_NVVDD=954.582155M(902.499974M,997.500002M)V 
MEAS_PEX_VDD=1.042621(997.499943M,1.1025)V 
MEAS_FBVDDQ=1.528877(1.425,1.575)V 
MEAS_DDC_5V=4.969013(4.75,5.25)V 
MEAS_PEX_PLL=1.050018(997.499943M,1.1025)V 
MEAS_3V3_FUSE=3.290271(3.135,3.465)V 
MEAS_12V_F=12.022661(11.4,12.6)V 
PS_OFF=(4.75,5.25)V 
PS_OPEN=(-39.999999M,39.999999M)V 

BOARD P2010 PASS

[LOGINFO]
BoardSN=0421916017196
ProductName=P2010
ProductNumber=11392951-00
ProgramName=P2010-11392951-00-V00
MachineID=ICT12
FixtureID=ICTJ101
Station=ICT
OperatorID=1316873
ERRORCODE=0
Result=PASS
FLAG=YES
"13-MAY-16  08:34:36

**Comment by Svetomech** [comment]
Workaround: you can create a temp file that would only contain INI data and then parse it.

**Comment by rickyah** [comment]
As that's not an INI file you can't use this library to parse it fully. As @Svetomech suggested, you could parse a subset of the file and parse only that subset, however you probably should not be adding a dependency on a third party library for such a simple feat.
I would just read the whole file, search for a line starting with `BoardSN`, and read the value on that line starting at '=' character.
