### ISSUE TITLE
 SkipInvalidLines & missing key

### ISSUE THREAD

**Issue by Astorlights** [rickyah/ini-parser#119]
Hi, 
even though i set the SkipInvalidLines to true, the parser throws exception "key can not be missing" when the line is, well, invalid because of the missing key. 

I believe the fix is simple - in IniDataParser.cs alter
fucntion protected virtual void ProcessKeyValuePair(string line, IniData currentIniData) 
{             
   string key = ExtractKey(line);
   if (string.IsNullOrWhiteSpace(key) && Configuration.SkipInvalidLines) return; //add this
   ...
}

**Comment by rickyah** [comment]
Yep, it seems like a wrong behavior, I'll look into it, thanks
