### ISSUE TITLE
.NET Core/.NET Standard Library 1.6 compatibility

### ISSUE THREAD

**Issue by wdominik** [rickyah/ini-parser#122]
Are there currently any plans to provide a package for .NET Core/.NET Standard Library 1.6?

**Comment by Svetomech** [comment]
Is there any particular reason you'd want to use INI file format w/ .NET core?

**Comment by wdominik** [comment]
I need to communicate with another programm that uses INI files for transfer. Since I start this project from scratch, I'm evaluating the use of the .NET Core framework to be as portable as possible. It is not striclty necessary indeed, but since ini-parser is designed with portability in mind, I thought there might be plans to provide a .NET Standard 1.6 package.

**Comment by Svetomech** [comment]
Reasonable. @rickyah, any plans on that?

**Comment by rickyah** [comment]
Been disconnected from .NET platform development, so I had to read about what .NET standard is. I do not have any plans to create a .NET standard package, 
 I've tried to run [apiport](https://github.com/Microsoft/dotnet-apiport) on ini-parser's assembly and support on mono is really subpar, so I'll wait until all this recent changes are more mature. PRs are welcome of course.

**Comment by Nothing4You** [comment]
please reopen this. even if you don't plan to support this for now so it won't get lost.

**Comment by DenisDollfus** [comment]
Needed here too.

**Comment by rickyah** [comment]
I'll reopen this by petition, but if anyone can provide some links about how to create a library compatible with .net core 1.6 I'll be really happy :)

**Comment by Nothing4You** [comment]
Suggestions that were brought to me were having 2 different csproj files, one targeting .net fx 2.0, one targeting .net standard 1.6. since not all code is compatible with both .net versions a wrapper class should be created with an implementation for each version. then each csproj file should exclude the other versions implementation of that class.
there's only a few places where code isn't compatible: https://hosting.rep.pm/ini-parser/AnalysisReport.html (based on the current v3 dev branch)

**Comment by agc93** [comment]
@Nothing4You Couldn't this also be done with one csproj file, targeting both frameworks, then use conditional compilation symbols to ignore the incompatible parts?

**Comment by Nothing4You** [comment]
probably, i haven't messed with conditional csproj files so far.

**Comment by agc93** [comment]
@rickyah @Nothing4You I've opened #149 for enabling .NET Standard 1.3 support based on the current `development` branch (rather than 3.0).

Feedback and questions welcome.

**Comment by sylveon** [comment]
The library from NuGet works fine in .NET Core 2.0 BTW thanks to backwards binary compatibility.

**Comment by pulimento** [comment]
netstandard / netcore port in #188 🎊
