### ISSUE TITLE
System.NullReferenceException in default example!

### ISSUE THREAD

**Issue by Karaulov** [rickyah/ini-parser#124]
`   IniData data = new IniData(); `

`  data["Section1"]["key1"] = "value1"; `

`  Console.WriteLine(data.ToString()); `

i got System.NullReferenceException in string : `  data["Section1"]["key1"] = "value1";`

**Comment by Svetomech** [comment]
Call `data.Sections.AddSection("Section1");` beforehands.

**Comment by Karaulov** [comment]
But it is default example! 
Need fix it! 
I want to write values without adding sections!)))

**Comment by Karaulov** [comment]
https://github.com/rickyah/ini-parser/wiki/First-Steps

http://i.imgur.com/FtDD87A.png

**Comment by rickyah** [comment]
Yep, that's a bug: the section should be created automatically if it does not exist inside the INIData structure when you access with the indexer operator

**Comment by Karaulov** [comment]
You can fix it ? :hammer:

**Comment by markosole** [comment]
Hi,

I have similar problem. I'am using text box as an input to get section data keys. If I enter the Section that does not exist I get the error message and application crash. 

How can I fist check if section exist in the file and than gets it's data and print it in MessageBox? 

Thanks

**Comment by rickyah** [comment]
@markosole if you want to chack if a section exists you just need to call `myIniData.Sections.ContainsSection("new_section_name");`

To add the section yourself if it does not exists you use 
`myIniData.Sections.AddSection("new_section_name")`

**Comment by Karaulov** [comment]
But if section name UNKNOWN ? 

need feature to auto add sections! Please! :(

**Comment by rickyah** [comment]
If the section name is unknown you can't add a new section anyway 🙁

**Comment by Karaulov** [comment]
Anyway, need fix))) impossible? :(

**Comment by rickyah** [comment]
Yeah, i can fix it but will take time: I'm on Christmas holidays without access to my laptop. I've provided workarounds for that bug though, 

However I can't fix what's not broken: if your problem is that you don't know the name of the section this is an different problem and no code in my library will help you 😔

**Comment by markosole** [comment]
@rickyah thanks for reply. I have tried to implement that but could not figure it out. 
Here is my example:

`public static string IniFajl(string machineNr)
        {

            //Create an instance of a ini file parser
            FileIniDataParser fileIniData = new FileIniDataParser();
            var parser = new FileIniDataParser();
            IniData data = parser.ReadFile("Configuration.ini");


            string ipAddressMachineString = data["" + machineNr + ""]["ipAddr"];
            string portMachineString = data["" + machineNr + ""]["portNr"];

            IniData parsedData = fileIniData.ReadFile("Configuration.ini");
            Console.WriteLine("---- Printing contents of the INI file ----\n");
            Console.WriteLine("Remote devices: " + parsedData["" + machineNr + ""]["ipAddr"]);
            Console.WriteLine();

            MessageBox.Show("Data for submition  Machine : " + machineNr + "  IP Address : " + ipAddressMachineString + " : " + portMachineString);
            // return IP address to function SubmitData
            return ipAddressMachineString;
        }`

And my config file: 

`[23]
ipAddr=192.168.11.164
port=88
mac=
delay=500

[24]
ipAddr=192.168.11.174
portNr=88
mac=
delay=200`

I would like to first check if there is a [SECTION1234] and then show MessageBox. If there is no section i would like to show message "That number does not exist. Enter correct number to proceed."
This is my first C# app sorry for asking for help with this. 

Thanks

**Comment by rickyah** [comment]
@markosole 

```csharp
public static string IniFajl2(string machineNr)
{
    //Create an instance of a ini file parser
    FileIniDataParser fileIniData = new FileIniDataParser();
    var parser = new FileIniDataParser();
    IniData data = parser.ReadFile("Configuration.ini");


    if (data.Sections.ContainsSection(machineNr)) {
        string ipAddressMachineString = data["" + machineNr + ""]["ipAddr"];
        string portMachineString = data["" + machineNr + ""]["portNr"];

        Console.WriteLine("---- Printing contents of the INI file ----\n");
        Console.WriteLine("Remote devices: " + parsedData["" + machineNr + ""]["ipAddr"]);
        Console.WriteLine();

        MessageBox.Show("Data for submition  Machine : " + machineNr + "  IP Address : " + ipAddressMachineString + " : " + portMachineString);
        // return IP address to function SubmitData
        return ipAddressMachineString;
    }

    return string.Emtpy;
}
```

You were reading the configuration file twice. I've removed a line. I don't understand why are you concatenating with empty strings `"" + machineNr + ""` but I left the code there in case there is a reason

**Comment by Svetomech** [comment]
```csharp
public static string IniFajl(string machineNr)
{
    var parser = new FileIniDataParser();
    var data = parser.ReadFile("Configuration.ini");

   string ipAddress = String.Empty;

   if (data.Sections.ContainsSection(machineNr))
   {
       ipAddress = data[machineNr]["ipAddr"];
       string port = data[machineNr]["portNr"];

       Console.WriteLine("---- Printing contents of the INI file ----\n");
       Console.WriteLine($"Remote devices: {ipAddress}");
       Console.WriteLine();
                
       MessageBox.Show($"Data to submit  Machine: {machineNr}  IP Address: {ipAddress}:{port}");
    }
    else
    {
        MessageBox.Show("That number does not exist. Enter correct number to proceed.");
    }

    // return IP address to function SubmitData
    return ipAddress;
}
```
@markosole

**Comment by markosole** [comment]
@Svetomech Thanks man! This works. 
and @rickyah I got the error for `string.Empty` not defined. How ever, Svetomech solution worked. 
I am looking for a way how to store all sections and their ipAddresses in array and then show them in ListBox. I would use same array to make a PING test for each address in order to show it's status as "Online" or "Offline". Do you have any idea?
Thanks

**Comment by Svetomech** [comment]
@markosole Please, don't abuse _Issues_ page. ~~I helped you once because it was at least somewhat related.~~
There are other places to seek C# help. E.g. I'd be more than willing to help you [here](https://discord.gg/PVjJ6).

**Comment by rickyah** [comment]
@Svetomech, spot on. @markosole for generic programming questions you should use another place.

**Comment by Karaulov** [comment]
**rickyah,** need fix))) It is necessary, you just do not need to know for what)

**Comment by rickyah** [comment]
This is an Open Source project and I'm on vacation. If you really need it fixed ASAP, I accept PRs

**Comment by Karaulov** [comment]
@rickyah This project belongs to you, you are obliged to correct everything errors ! :))

**Comment by Karaulov** [comment]
@rickyah ,To correct this error it is necessary to understand your bad code, this bad code belongs to you and you shall correct all errors! :)

**Comment by rickyah** [comment]
There's were you are wrong, I'm not obliged to anything. I maintain this project in my spare time, but I do not have too much time to spare these days, nor my laptop; I'm answering using my phone.

You have a workaround for the bug that you stubbornly refuse to use. I've told you twice that I'll fix it, but just not right now. But you choose to keep demanding in a rude way. Here's some free advice: that kind of attitude won't get you anything here. 

As a matter of fact, I'm going to close this issue until you learn proper manners


And get off my lawn! 😉

**Comment by Karaulov** [comment]
@rickyah without autocreate sections need write more unused code. I download this parser only for easy using...
