### ISSUE TITLE
An unhandled exception of type 'IniParser.Exceptions.ParsingException' occurred in INIFileParser.dll - Version 2.3.0.0

### ISSUE THREAD

**Issue by dcrispgit** [rickyah/ini-parser#129]
I am using Visual Studio 2015 community. 

I have tried to run your  ini-parser/src/INIFileParser.Example/Program.cs file

I get the following exception
"An unhandled exception of type 'IniParser.Exceptions.ParsingException' occurred in INIFileParser.dll

Additional information: Could not parse file test.ini while parsing line number 0 with value '' - IniParser version: 2.3.0.0"

I first found this bug with my own code and thought it was just me so I tested using your own working examples.     Your working examples dont work? 

The INI file I am trying to load is :   ini-parser/src/INIFileParser.Example/TestIniFile.ini

**Comment by caverna** [comment]
I just run the INIFileParser.Example.exe without any problem (using the version 2.3.0).
May you please write down the complete exception message?

**Comment by dcrispgit** [comment]
This was a false alarm at the end of a very long work week for me.  
After my break I retested the code and worked out the fault. 

The following line defines where the file to be read can be found.   If the file is not found it throws an exception rather than handling the lack of file properly. 

IniData parsedData = fileIniData.ReadFile("test.ini");

The default search folder for the file appears to be different to .\ 

The code does not appear to look in the default current working directory first for the ini file.
