### ISSUE TITLE
What is the call order of IniDataParser?

### ISSUE THREAD

**Issue by ianmakecode** [rickyah/ini-parser#131]
Ricky, it would be outstanding if you would be willing to add call-hierarchy information to the wiki page regarding the IniDataParser.  Would be helpful in creating the proper logic necessary for custom IniDataParsers.

Thanks,
Ian Ray

**Comment by rickyah** [comment]
Is a good idea! Will do👍🏻

**Comment by ianmakecode** [comment]
awesome library!

**Comment by rickyah** [comment]
I've updated the page with the algorithm steps:

https://github.com/rickyah/ini-parser/wiki/Customizing-the-parser-algorithm

I'm closing the issue but leave a comment here if you need anything else @ianmakecode

**Comment by ianmakecode** [comment]
Ricky,

Great job!  Thanks a ton! 10/10 library
