### ISSUE TITLE
how to get only all section name

### ISSUE THREAD

**Issue by nimeshc64** [rickyah/ini-parser#137]

**Comment by rickyah** [comment]
I don't know if I did understand your question completely. Do you need to get the names of all the sections in a file? If that's the case, you can iterate `inidata.Sections` and query the `SectionName` property:

```csharp
var names = new List<string>();
foreach (var section in parsedData.Sections)
{
    names.Add(section.SectionName);
}
```

Or you can use LINQ:

```csharp
var names = (from s in iniParser.Section select s.SectionName).ToList();
```

**Comment by nimeshc64** [comment]
thanks
