### ISSUE TITLE
Proposal: Allow writing comments to file

### ISSUE THREAD

**Issue by Bert-Proesmans** [rickyah/ini-parser#138]
Hi

I'm using this library and i noticed the parser is capable of removing comments from input files.
Opposing to this there is no interface provided to WRITE comments to ini files.

It's not a life critical feature, would it be worth implementing functions that take comments to be written (at the section level) above/underneath sections?

Bert

**Comment by rickyah** [comment]
Thanks @Bert-Proesmans. The library actually allows to create new comments, however the API is not as nice as accessing section and key/values.

Take a look at [`SectionData.LeadingComments`](https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/Model/SectionData.cs#L131) and [`KeyData.Comments`](https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/Model/KeyData.cs#L52) both expose a `List<string>` you can use to add new comments to each section or key/value element. Comments will be put before the element when creating the string for the `IniData` structure

(*) There's is a `SectionData.TrailingComments` property. Don't use it, it is flawed.

**Comment by Bert-Proesmans** [comment]
Thanks for the pointers!

I had used the Github search with 'comment' and the test cases showed first, so somehow i thought they were all about comment filtering.

Regarding documentation; i read the wiki pages before trying to prototype something myself.
It's super easy to get started and READ ini files, but trying to write a file (from scratch) could be fleshed out more. I basically just went with the reading examples and tried to transform it to write files. 
This caused me to miss the SectionData structure since it's practically shorted through dictionary access on IniData and the SectionDataCollection.AddSection method.

Thanks again

Bert

**Comment by rickyah** [comment]
I've added a brief section on the readme so people know that you can modify comments for an ini file
