### ISSUE TITLE
Merging files example doesn't seem to work

### ISSUE THREAD

**Issue by KennethScott** [rickyah/ini-parser#140]
I may just be missing something, but I can't seem to get the example in the README.md for merging **files** to work.
````csharp
    var parser = new IniParser.Parser.IniDataParser();
    IniData config = parser.Parse("global_config.ini");        
    IniData user_config = parser.Parse("user_config.ini");   
    config.Merge(user_config);
````
Produces an exception:
`ParsingException: Unknown file format. Couldn't parse the line: 'global_config.ini'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0`

It looks like parser.Parse() is actually supposed to take a *string* of raw ini data as opposed to a *filename*..?  Would I need to use a **FileIniDataParser** to first read the ini files into memory?

**Comment by rickyah** [comment]
You are right that `IniParser.Parse` requires an string with the contents of the ini file, so the example is wrong, I'll change it.

You can use FileIniDataParser or whatever method you prefer to read the contents of the file, e.g:

```
var parser = new IniParser.Parser.IniDataParser();
IniData config = parser.Parse(File.ReadAllText("global_config.ini"));
IniData user_config = parser.Parse(File.ReadAllText("user_config.ini"));
config.Merge(user_config);
```

**Comment by rickyah** [comment]
Fixed
