### ISSUE TITLE
How can i add custom comment style ？

### ISSUE THREAD

**Issue by ljporljp** [rickyah/ini-parser#141]
Hi, I want to add "//" comment style to the ini structure, how just can i do ?  Would you please give me a example ?

**Comment by rickyah** [comment]
Please search in the wiki page https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior for `CommentString`

**Comment by ljporljp** [comment]
Ok, i did that ,but i want to use two or more “CommentString” , Did the ini-parser support ? ps. there are many config ini that mixed with "#" , ";" and "//",[(-,-)headachy]
