### ISSUE TITLE
System.Reflection compatibility in .net standard 1.6

### ISSUE THREAD

**Issue by rickyah** [rickyah/ini-parser#145]
Change all usages of Type method calls to use TypeInfo. The latter is supported in .net standard 1.6 API 

GetExecuting assembly is not a supported API so that has to change too.

**Comment by Nothing4You** [comment]
This change is not supported in .NET 2.0. If we want to keep .NET 2.0 support there will have to be different ways to access this (e.g. wrapper methods).

**Comment by rickyah** [comment]
For version 3 I don't care anymore for .NET 2.0, it's been its 10th birthday anyway :D

**Comment by Nothing4You** [comment]
What's the minimum version you want to support?

**Comment by rickyah** [comment]
I've been thinking about it since you create the code clean up PR #143 

Technically, if I want this lib to still support unity engine, it should be .net 3.5. However I don't know the current version of mono included by the latest unity 5.6. On top of that, unity includes some new compiler features although it uses an older version of the framework.

I need to gather some more information, for now is .net 3.5

**Comment by Nothing4You** [comment]
Just for reference, by targeting .net standard 1.6 the .NET Framework 4.6.1+ will be supported.
https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by pulimento** [comment]
netstandard version!! #188
