### ISSUE TITLE
support for unicode

### ISSUE THREAD

**Issue by MasihAkbari** [rickyah/ini-parser#147]
hi i use this line of code  
`data["setting"]["SUBJECT"] = "سلام";`
`parser.WriteFile("config.ini", data);`

this text is in unicode (persian) but in config file it saves as ???????? chars.
how can i use unicode with this library?

**Comment by Svetomech** [comment]
@MasihAkbari Change `parser.WriteFile("config.ini", data);` to `parser.WriteFile("config.ini", data, Encoding.UTF8);`.

**Comment by MasihAkbari** [comment]
thanks that's works like a charm

**Comment by Svetomech** [comment]
No problem.

**Comment by rickyah** [comment]
I need to put that in the documentation, is not the first time is asked

**Comment by rickyah** [comment]
And for the new version is probably safe to actually use unicode as default

**Comment by Svetomech** [comment]
Better yet, just default writing to use UTF8 (since . Unless it causes some compatibility problems I'm unaware of.
