### ISSUE TITLE
Signing issues in v2.5.0

### ISSUE THREAD

**Issue by rickyah** [rickyah/ini-parser#151]
ini-parser 2.5.0 seems to have some signage issues. Strong-name verification fails on my end, with this exception. I don't think the problem is on my end since 2.4.0 works just fine.

"Could not load file or assembly 'INIFileParser' or one of its dependencies. Strong name signature could not be verified. The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)"

**Comment by yuuhhe** [comment]
crash on web application only

**Comment by rickyah** [comment]
A new nuget version 2.5.2 with strongname signing is available
https://www.nuget.org/packages/ini-parser/2.5.2

**Comment by flmontpetit** [comment]
Thanks a lot for this

**Comment by rickyah** [comment]
Thank you for letting me know! 

Seems like a bug in VS, or a problem when I migrated from xamarin studio to the new "version" visual studio mac. The project is actually configured to sign the library's dll, but it does not work. It just skips it. So I had no idea I pushed the library without a strong name (signed)

Fortunately the feedback was quick! ;)

**Comment by yuuhhe** [comment]
well done
