### ISSUE TITLE
Proposal: Default Value if key or section doesn't exist

### ISSUE THREAD

**Issue by tephyrnex** [rickyah/ini-parser#153]
First...Thanks for the handy ini-parser.  Very good work indeed.

Saying that, it sure would be handy to allow a default value in for keys rather than throwing exceptions or returning null values.

_MyBoolValue_ = bool.Parse(data["Section"]["Key"],  _false_);

is a far sight easier to read/write than a bunch of try/catch blocks or manually checking for each section and key existence.

**Comment by caverna** [comment]
@tephyrnex, may I suggest you to use this extension?
https://gist.github.com/caverna/b8d7ccb8b06c2995cb22
So you can use just like that:
<code>MyBoolValue = data["Section"]["Key"].To\<bool\>()</code>
Or with default value:
<code>int MyIntValue = data["Section"]["Key"].To(1234)</code>

**Comment by rickyah** [comment]
I think the solution @caverna suggests is elegant enough. I do not wish to add code that convert between types because values in an ini could represent custom types. Also I think in this case the `null` keyword is semantically accurate: you asked for a value that do not exist.
