### ISSUE TITLE
Comment after section throws exception

### ISSUE THREAD

**Issue by EmmanuelAtx** [rickyah/ini-parser#155]
Unknown file format. Couldn't parse the line: '[Update]	; 4565454'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0

When you try to put a comment after a section, the line can't be parsed.

**Comment by rickyah** [comment]
@EmmanuelAtx  would you mind to post an ini file to reproduce the bug? I can't seem to trigger it

**Comment by EmmanuelAtx** [comment]
Thank you for asking. Here you are:

[update_FR]	; My Comment
newVersion=6.14.0.2411
updateChance=1000
updateChanceBeta=0

Unknown file format. Couldn't parse the line: '[update_FR]	; My Comment'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 32 with value '[update_FR]	; My Comment' - IniParser version: 2.5.2.0

**Comment by secretwpn** [comment]
Actually I can't get it to work with any comments. When my file doesn't have comments - parsing and saving goes well, but if I have something like
`[SECTIONNAME]`
`PROP1=val1`
`# comment`
`PROP2=val2`
(doesn't matter which line I add a comment to) reading fails with error similar to described above

Also if I do this
`PROP=VAL #comment` - comment gets interpreted as part of the val. Though I'm not sure INI spec allows this usage when the comment is on the same line with property. Ignore this if it is not up to spec.

I think one good test would be to open php.ini file - as it has loads of comments 

UPDATE/CORRECTION: this goes to FileIniDataParser. If I use plain IniDataParser everything works.

**Comment by monty124** [comment]
I can confirm I am seeing this behaviour too, comments on any line with any comment character causes a parsing error
{"Unknown file format. Couldn't parse the line: 'file.ini'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 1 with value 'file.ini' - IniParser version: 2.5.2.0"}
tried both FileIniDataParser and IniDataParser 
only thing that works is to remove comments from ini file
i'd ditch this and go back to ConfigurationManager.AppSettings but it seems to be broken with mono
