### ISSUE TITLE
Spaces between key, assignment and value

### ISSUE THREAD

**Issue by mestiso** [rickyah/ini-parser#158]
AssignmentSpacer seemed like the right value to tweak but it was already set to an empty string and values are written as:
foo = bar

How can I get this to write lines without the space between the key, assignment and value like:
foo=bar

**Comment by rickyah** [comment]
Mind you to show me a snippet of the code you are using 

The IIniDataFormatter has a `Configuration` field. You need to set the `AssignmentSpacer` there. Yes, I know is nowhere near as intuitive, and it will change, but in the meantime I can probably help you out if I see the code.

**Comment by rickyah** [comment]
I've just tested running `write_key_and_value_without_blanks` and it works
