### ISSUE TITLE
UTF-8 is always set

### ISSUE THREAD

**Issue by Outworldz** [rickyah/ini-parser#159]
Earlier versions, such as 2.5.2 saved the INI files as ASCII.  Later versions save them as UTF-8. Mysql will not run if My.Ini  is UTF-8. fml, I rolled back and it works

**Comment by rickyah** [comment]
You can set up the encoding when persisting the Ini data to a file. If you are using FileIniStream, you can use the method `WriteFile(string filePath, IniData parsedData, Encoding fileEncoding = null)` calling it like
`iniFileStream.WriteFile("./my.ini", myData, Encoding.ASCII)`

https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/FileIniParser.cs#L121

If this didn't solve the problem, comment there again and I'll reopen the issue 😃

**Comment by Outworldz** [comment]
Lovely, Thank you!

Fred

**Comment by Svetomech** [comment]
@Outworldz If you are interested when the change was made: https://github.com/rickyah/ini-parser/issues/147
