### ISSUE TITLE
Lines with '#' at start, cause Exception.

### ISSUE THREAD

**Issue by Karaulov** [rickyah/ini-parser#161]
I always got "Error" in this code:
```
try
{
    data = parser.ReadFile(ConfigFileName);
}
catch
{
    Console.WriteLine("Error");
}
```

**Comment by Karaulov** [comment]
Sorry problem in 'INI' file :)  (bad comment)

**Comment by Karaulov** [comment]
Lines with '#' at start, cause **Exception**.

**Comment by domshifter** [comment]
I got the same problem, comment lines starting with an '#' cause the following exception:
`Unknown file format. Couldn't parse the line: '# comment'. while parsing line number 0 with value '' - IniParser version: 2.5.2.0 while parsing line number 4 with value '# comment' - IniParser version: 2.5.2.0 `

I know that comment lines shoud be started with a semicolon, althrough it seems to be pretty common to write comments in the following way:

![image](https://user-images.githubusercontent.com/16257869/34608729-07020be6-f21a-11e7-94a2-a9c6295668c5.png)

For example, the my.ini default configuration for MySQLServer also uses that style of commenting.

Would it be possible to add support for such comments?
I'd love to add this feature with a pull request, if it's not contrary to the intention of the inventor. :-)

**Comment by sportflier** [comment]
I'm having the same issue and use case as domshifter; I'm trying to use this library to parse MySQL ini files, but am unable to because of the exception thrown on comments in these files.

**Comment by sportflier** [comment]
domshifter, Karaulov: 

Digging through source code on this project, I found it is possible to get desired functionality (for me) to parse MySQL ini files, without altering ini-parser project source:
`                    var iniParserConfig = new IniParser.Model.Configuration.IniParserConfiguration()
                    {
                        CommentString = "#",
                        SkipInvalidLines = true
                    };
                    var iniDataParser = new IniParser.Parser.IniDataParser(iniParserConfig);
                    var parser = new FileIniDataParser(iniDataParser);
                    var data = parser.ReadFile(myiniPath);
`
The documentation might benefit by including a use case like this.

**Comment by rickyah** [comment]
Documentation does states that you can change the character (the substring, actually) used as comment:
https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior

However @sportflier 's idea is good: it would be an improvement to create a example in the *Getting Started* section to cover this common case. I've added an issue for that 
https://github.com/rickyah/ini-parser/issues/163

**Comment by Karaulov** [comment]
@rickyah but how to add new comment character? (without replace default)

**Comment by Karaulov** [comment]
` parser.Parser.Configuration.CommentRegex =  new Regex("(#|;).*");`

**Comment by rickyah** [comment]
The library does not supports multiple comment strings. The only solution right now is to create a child class of `IniParserConfiguration` and override _strCommentRegex

You can override CommentRegex as you did in your sample code, but beware: it will be overwritten if you assign something to CommentString. That property (`CommentRegex`) should be read only, is a mistake
