### ISSUE TITLE
Can't change default Encoding from WriteFile

### ISSUE THREAD

**Issue by eduardomozart** [rickyah/ini-parser#165]
Hello rick and Community!

Before everything, I just want to thank you for your work on this!

I'm using ini-parser into a .NET Core C# project to change the config of a legacy application (ClamWin). But I'm having a little trouble on it. It reads the file correctly, but when it is written to the disk, the ClamWin can't read the config from file.

I used WinMerge to compare the two ini files (I was suspecting that maybe ini-parser breaks the format, but it was not the case) and the two files were identical. The only thing that changes were the Encoding.

I know that it isn't exactly a "bug", most applications read UTF-8 files without problems, only legacy applications doesn't use it as it should.

When I set "UTF-8 (without BOM)" at Notepad++, the file generated by Ini-Parser were read successful by ClamWin. So I had to write an helper function that runs after Ini-Parser writes the file: it reads all files content and save it to a new encoding (UTF-8 without BOM). I'm posting it below if it is useful. But it would be amazing if I could set the file encoding directly on Ini-Parser.

```
private static void ConvertToUTF8WithoutBOM(string ConfFile)
        {
            Console.WriteLine("[Program.cs] [INFO] Convert to UTF-8 (without BOM): " + ConfFile);
            // https://stackoverflow.com/questions/2502990/create-text-file-without-bom
            Encoding utf8WithoutBom = new UTF8Encoding(false);
            string TempFileName = Path.GetTempFileName();
            TextWriter tw = new StreamWriter(TempFileName, false, utf8WithoutBom);
            
            // https://stackoverflow.com/questions/286533/filestream-streamreader-problem-in-c-sharp
            using (StreamReader Reader = new StreamReader(ConfFile))
            {
                while(!Reader.EndOfStream)
                {
                    tw.WriteLine(Reader.ReadLine());
                }

                Reader.Close();
            }

            tw.Close();

            Console.WriteLine("[Program.cs] [INFO] Deleting " + ConfFile);
            File.Delete(ConfFile);
            Console.WriteLine("[Program.cs] [INFO] Moving \"" + TempFileName + "\" to \"" + ConfFile + "\"");
            File.Move(TempFileName, ConfFile);
        }
```

**Comment by eduardomozart** [comment]
My fault. Searching on older cases I could find a solution at #159, but now I migrated the code to Python so I couldn't test it.

**Comment by rickyah** [comment]
This was opened and closed so quickly that I totally missed it 😮  

Thanks @coldscientist for the comments, glad this library helped you 😄
