### ISSUE TITLE
Remove Trailing Newline After Saving

### ISSUE THREAD

**Issue by Aleksbgbg** [rickyah/ini-parser#166]
Is it possible to get rid of trailing new lines when saving files?

**Comment by rickyah** [comment]
Sorry for taking so long in anwering

Writing files is not one of the lib top priorities, so custom writing is limited. 
As a workaround I suggest removing the lines from the file once is written. If you need more fine-grained writting options you will need to iterate through the iniData file and writing the values to a file manually
