### ISSUE TITLE
Saving Data[Using WriteFile] Got Problems?

### ISSUE THREAD

**Issue by HowToDoThis** [rickyah/ini-parser#170]
Hello There, I'm New To This Ini-Parser... 
I Wanted To Do Is While Click The Button And Save 3 Textbox Data To A Ini File, Then When I Write A Simple Command > iniData[name][key] = Textbox1.Text; [Same Thing As Other 2] < To Set The Key Value. [So Far Here Got No Problems] After Set The Key Value, It Will Proceed To WriteFile. While Saving To The Ini Files, It Will Cause Some Duplicate Problems Like Textbox1.Text is aaa, Save Successfully. Then Second Time Click The Button, Textbox1.Text is aab, Then The Ini File Will Appearing This.
[aaa]
key=value
[a]
[aa]
[aab]
key=value

And Here is Full Code Of My Project https://hastebin.com/ositivizud.cs

**Comment by rickyah** [comment]
Each time the StudentID.Text changes in StudentID_TextChanged() you access the iniData like this
`UserName.Text = iniData[StudentID.Text]["Username"];`
 iniData[StudentID.Text] creates a section whose name is the contents of StudentID.Text. So each time you press a key inside the form you generate a new section, which is the problem you seem to have.

This does not seem related to the lib, so I'll close the issue

**Comment by HowToDoThis** [comment]
So means that I cannot use TextChange For Auto check file and gave me data from it, cause it will auto generated a new appname?

**Comment by rickyah** [comment]
My Winforms is rusty, but you may try doing it using the event focus lost so the code that creates the section it is only triggered once
