### ISSUE TITLE
could support dotnet core?

### ISSUE THREAD

**Issue by GenKnight** [rickyah/ini-parser#174]
Hi, I wana use it in Linux OS with dotnet core 2.0
could you plz add support to it?

**Comment by rickyah** [comment]
Support for dotnet core is planned for version 3.0, but no ETA yet. I'm actually developing with dotnetcore 2.1

**Comment by salaros** [comment]
@GenKnight hey, I have recently created [a similar library](https://github.com/salaros/ConfigParser)
Please try it out and star if you like it

**Comment by keeratsingh** [comment]
@rickyah Any updates on plan to support dotnet core ?

**Comment by pocketbroadcast** [comment]
Wouldn't a port to dotnet standard be a more general approach?

Used the ini-parser with dotnet standard 2.0. (So feel free to contact me for a pull request.)

**Comment by salaros** [comment]
@pocketbroadcast indeed, .NET Standard support covers both .NET Framework, .NET Core as well as Mono and other implementations.
Instead of porting this library I decided to create my own. You can check it [here](https://github.com/salaros/config-parser/)

**Comment by rickyah** [comment]
I've recently set up my environment to use dotnet core, and my intention is to target dotnet standard 2.0 
This will trigger a new mayor version of the library though, expect a 3.0 version soon

**Comment by pulimento** [comment]
see https://github.com/rickyah/ini-parser/pull/188 (it's done 👍  )
