### ISSUE TITLE
Extra bytes inserted at start of first line

### ISSUE THREAD

**Issue by InteXX** [rickyah/ini-parser#175]
The parser is writing three invisible, non-editable bytes (except in a hex editor) at the very beginning of a given .ini file:

> `ef bb bf`

Naturally, applications are refusing to read the file.

I'm able to work around it like so:

    oBytes = File.ReadAllBytes(sPath).ToList
    oBytes.RemoveAll(Function(B) B.IsIn(New Byte() {239, 187, 191}))
    File.WriteAllBytes(sPath, oBytes.ToArray)

However, I'd rather not have to do this if at all possible.

Is anyone else experiencing the same problem?

**Comment by rickyah** [comment]
That sequence is the Byte Order Mask (BOM) for UTF-8 files. Try setting the encoding of the file to other encoding like ASCII and it should work.

If you need the file to be in UTF-8, then you should write the IniData to a string yourself using any of those two methods:
https://stackoverflow.com/questions/2437666/write-text-files-without-byte-order-mark-bom

Please note that some editors (specially the Microsoft ones, like Visual Studio Code, Visual Studio for Mac) have the bad habit of adding the BOM without asking nor notifying if you open a UTF-8 file by default

**Comment by InteXX** [comment]
@rickyah 

That did the trick, thanks. ASCII is fine.

Just curious... Wikipedia doesn't have an entry for Byte Order Mask. It does have one, however, for [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark). Are they synonymous?

**Comment by rickyah** [comment]
No they are not synonymous, is just me who can’t spell right  :smile:

The proper term is Byte Order *Mark*

Glad it worked!

**Comment by InteXX** [comment]
Aha. Good man  :-)

Great job with this. Thanks for all you do.
