### ISSUE TITLE
Warning: 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1'

### ISSUE THREAD

**Issue by malmil** [rickyah/ini-parser#178]
The ini-parser works as expected, but I get this warning:

warning NU1701: Package 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.

Any idea how to get rid of the warning or possible errors that may occur due to this warning?

**Comment by rickyah** [comment]
Hi @malmil, can you specify which branch were you using when this error triggered?
Version 2.5.2 should be targeting an even older .net version that 4.6, definitely not netcore

**Comment by pulimento** [comment]
This PR (#188) adds support to NetCore
