### ISSUE TITLE
Bool test for Sections and Keys

### ISSUE THREAD

**Issue by imaginarytools** [rickyah/ini-parser#181]
While upgrading some of my clients I realized that I am trying to use some config options that aren't there yet, which of course results in a NullReferenceException . It would be great if I could do something like this:

        public static void ValidateConfig() {
            if (INIConfig["Settings"] == null) {
                INIConfig["Settings"]["Setting1"] = "Value1";
            }
            if (INIConfig["TimeSettings"] == null) {
                INIConfig["TimeSettings"]["NewSetting"] = "false";
            }
            WriteConfig();
        }

Or    if (INIConfig["Settings"].Exists()) ...

I am not sure if there is a better way to test for those than what I have found by doing try catches, but this would be nice.

**Comment by rickyah** [comment]
You can check if a section or key exist with: 
```c#
if (INIConfig.ContainsSection("Settings")) {
   INIConfig.Sections.["Settings"]["Setting1"] = "Value1";
}
if (INIConfig.Sections.ContainsSection("TimeSettings")) {
      INIConfig["TimeSettings"]["NewSetting"] = "false";
}

WriteConfig();
```
