### ISSUE TITLE
Merge happens with undesired keys strings

### ISSUE THREAD

**Issue by sumankumar** [rickyah/ini-parser#193]
During merge of ini files , if the old file contains a key similar to the key ( ie strings starting with same substring)  in the new file.
Then after merge the old key still remains as shown in left image in attached pic.
![bugForOpenSource](https://user-images.githubusercontent.com/431614/70527933-b3be8880-1b55-11ea-8a71-c47889625159.png)

Could this be a bug in the source code 
and can be fixed just by adding additional 'AddUniqueKey()'  in IniFileParser\Model\PropertyCollection.cs :

```
       public void Merge(PropertyCollection keyDataToMerge)
        {
            foreach (var keyData in keyDataToMerge)
            {
                AddUniqueKey(keyData.KeyName);
                GetKeyData(keyData.KeyName).Comments.AddRange(keyData.Comments);
                this[keyData.KeyName] = keyData.Value;
            }
        }

  public bool AddUniqueKey(string keyName)
        {
            Property returnValue = null;
            if (!_keyData.ContainsKey(keyName) && _keyData.TryGetValue(keyName,out returnValue))
            {
                _keyData.Add(keyName, new Property(keyName));
                return true;
            }

            return false;
        }
```

**Comment by rickyah** [comment]
Hi @sumankumar can you please put here which version of the library are you using? I can't seem to replicate this bug in version 2.5.2
