### ISSUE TITLE
Feature request: support keys without values

### ISSUE THREAD

**Issue by RayCarrot** [rickyah/ini-parser#196]
The .ini file Ubisoft uses for their early Windows applications has a section which looks like this:
```ini
[INSTALLED PRODUCTS]
RAYMAN2
RAYEVEIL
```
This section has keys, but without any values or equal signs. In the latest version of the parser it doesn't handle these. If I set it to skip invalid lines they won't be written to the file upon saving. As of now I have to copy and insert them manually each them I edit the file using the parser.
My request is to allow these type of keys, or list items, to be handled in some way.

**Comment by rickyah** [comment]
I've implemented the feature, but I'm closing this issue as this is duplicated from https://github.com/rickyah/ini-parser/issues/196

It will be available in version 2.6.0, but you can access it right now from branch: https://github.com/rickyah/ini-parser/tree/release/2.6.0

**Comment by rickyah** [comment]
I've implemented the feature, @RayCarrot 
It will be available in the upcoming version 2.6.0, but you can access it right now from branch: https://github.com/rickyah/ini-parser/tree/release/2.6.0
