### ISSUE TITLE
UTF8 Endoding does not work 

### ISSUE THREAD

**Issue by michalss** [rickyah/ini-parser#198]
Hi,

I have a huge issue, i was trying to use your parser for localization purpose, but it does not work for UTF8 cahracters.

**Comment by michalss** [comment]
sorry im and idiot, i forget to chech for ReadFile.. :(

**Comment by rickyah** [comment]
Don't beat yourself @michalss: this is something that has bitten many people before you, so I'm the one to blame: is not a good design from my part. Glad you found a solution!
