### ISSUE TITLE
no spaces between equal sign

### ISSUE THREAD

**Issue by cdmaxy** [rickyah/ini-parser#205]
Hello,

how can i remove the spaces before and after the equal sign
I need it in this form:
```
[Local]
launcherVersion=0.0.3
gameName=Example
systemTarget=Win
```

not

```
[Local]
launcherVersion = 0.0.3
gameName = Example
systemTarget = Win
```

**Comment by vermiceli** [comment]
Hi @cdmaxy,
When creating a IniParser, simply pass a `IniParserConfiguration` that includes the `AssigmentSpacer` configuration.

`FileIniDataParser INIParser = new FileIniDataParser(new IniDataParser(new IniParserConfiguration() { AssigmentSpacer = string.Empty }));`

Now when you write the INI data, it'll not include any spaces between the equals sign and the key and value.

The parser configuration properties are defined here: https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior
