### ISSUE TITLE
AllowKeysWithoutSection is fully ignored...

### ISSUE THREAD

**Issue by Zorono** [rickyah/ini-parser#208]
AllowKeysWithoutSection is fully ignored...
reference: https://github.com/rickyah/ini-parser/blob/development/src/IniParser/Model/Section.cs#L27-28

example code:
```
           FileIniDataParser INIParser = new FileIniDataParser();
           IniData INIConfig = new IniData();
           //...................
            INIConfig[""]["pagesize"] = trackBar1.Value.ToString(); // the problem
            INIParser.WriteFile("config.ini", INIConfig);
```

Example INI File:
```
pagesize = 50
maximized = 1
secretpass = ABCzev0458
```

i just need to fetch the value of a key which isn't linked to any section...
Expected value: `50`
but it always results in the Runtime error `section name can not be empty`...

**Comment by vermiceli** [comment]
Hi Zorono,
A few things to clear up.  It seems you are trying to read from an INI, but the code you shared shows you creating an INI file.  Regardless, I can help you here.

1.  To access a key from an INI file without a section, you need to use the `.Global` property.  This goes for both reading and writing.  You cannot simply pass an empty string to the headers like you are doing in your example.

`INIConfig.Global["pagesize"] = trackBar1.Value.ToString();`

2.  The `AllowKeysWithoutSection` configuration property tells the parser whether or not to allow keys that are not in a section (global keys) when reading an INI file.  The default value for this configuration is true.  It does not change anything about how to access keys in the INI file.  If you were to set `AllowKeysWithoutSection` to false, your code would fail with an error similar to 

> key value pairs must be enclosed in a section

**Comment by Zorono** [comment]
Thanks a lot for explaining and correcting my stupid issues.... <3
