### ISSUE TITLE
© gets rewritten as ?

### ISSUE THREAD

**Issue by shaggygi** [rickyah/ini-parser#217]
Seems like the copyright system © gets changed to '?' when using `WriteFile` method.

I noticed this when trying to set a value to a specific attribute and other attributes that have © are getting changed to ?.

```csharp
_data[sectionName][attributeName] = attributeValue;
_parser.WriteFile(_filePath, _data);
```

**Comment by Willy-Kimura** [comment]
Seems like you'll need to specify the type of encoding:

```c#
_parser.WriteFile(_filePath, _data, System.Text.Encoding.UTF8);
```

**Comment by shaggygi** [comment]
I figured it out, but forgot to close out.  It turns out the files I'm working with is not supported by .NET Core (as it is a specific Windows encoding).  The files are supposed to be updated to UTF-8 in the near future, so I can use with .NET Standard/Core at that time.  Closing issues.
