### ISSUE TITLE
Duplicated key exception in Engine.ini(UE4)

### ISSUE THREAD

**Issue by KulaGGin** [rickyah/ini-parser#218]
Engine.ini:
```
[Core.System]
Paths=../../../Engine/Content
Paths=%GAMEDIR%Content
Paths=../../../Engine/Plugins/Wwise/Content
Paths=../../../Engine/Plugins/Runtime/CriWare/Content
Paths=../../../TekkenGame/Plugins/NetCommon/Content
Paths=../../../TekkenGame/Plugins/CosmosWebApi/Content
Paths=../../../TekkenGame/Plugins/NeoFur/Content
```
When I try to parse this with:
```
protected string EngineIniPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "\\TekkenGame\\Saved\\Config\\WindowsNoEditor\\Engine.ini";
var iniData = _parser.ReadFile(EngineIniPath);
```
I get the exception `Duplicated key 'Paths' found in section 'Core.System while parsing line number 0 with value '' - IniParser version: 2.5.2.0"} | System.Exception {IniParser.Exceptions.ParsingException}`:
![devenv_e3cn7Rk18Y](https://user-images.githubusercontent.com/16989713/84903893-56346700-b0b7-11ea-8e13-5f34d4b6740a.png)

**Comment by dechowdev** [comment]
Have you tried the DuplicateKeys option within the configuration of the library?

https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior

**Comment by KulaGGin** [comment]
Thanks, I'll try it out. I went through the documentation before creating this issue but missed it.
