### ISSUE TITLE
Parsing Error: Unknown file format. Couldn't parse the line: '[Way-Keyword-*##59710880]'.

### ISSUE THREAD

**Issue by cyberbox2001** [rickyah/ini-parser#53]
while I  open a ini file with section name as  [Way-Keyword-_##9710880] will get this Exception Unknown file format. Couldn't parse the line: '[Way-Keyword-_##59710880]'.
how can i handle this error?

**Comment by SteveJobsCousin** [comment]
i'm getting the same issue : 

```js
Error XDG0006 : 
Unknown file format. Couldn't parse the line: ' ( some weird Chinese sentence here )  '. 
while parsing line number 0 with value '' - IniParser version: 2.5.2.0 
c:\......\Code\Beta\V2.0\MVVM\Setup_Dictionary.xaml 18
```

and the `Setup_Dictionary.xaml` is being called inside `App.xaml `  like : 
```xaml
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="MVVM/Setup_Dictionary.xaml" />
</ResourceDictionary.MergedDictionaries>
```

- project : WPF Desktop Application, NetFramework 4.7.2
- Editor : Visual Studio 2022 . 
- Windows 10 .
