### ISSUE TITLE
Same line comments

### ISSUE THREAD

**Issue by rickyah** [rickyah/ini-parser#60]
Right now comments in the same line like this:
`key1 = value ; this is an important configuration setting`
are **not** parsed as comment, but as part of the value (i.e. the value for key `key1` is `value ; this is an important configuration setting`)

The library also need some way to preserve those kind of "same line comments" so they are persisted correctly if we convert the IniData back to a string

**Comment by seveseve** [comment]
Does the INI format really allow comments which are not starting at the beginning of a line? I know that the GetProfileString-WinAPI calls do not support these kinds of comments. In the german Wikipedia article they also say that it is not allowed but in the english version there is a heading called "Varying features". Imho these varying features are not part of the "original" INI format but some kind of extended INI. So we need a decision :zap:

**Comment by rickyah** [comment]
I've been thinking on this and I think you are right @seveseve On top of that supporting this kind of behaviour could break backwards compatibility in some cases. Let's suppose we have an ini file with strings for localizations, if the library starts treating characters that appear in the middle of a line as comments it could break the previous behavior in a non-obvious way
```
[en-us]
greeting = hello world; I'm here
```

So I've decided to not implement this feature.
