### ISSUE TITLE
ReadFile excepts with no recovery if INI contains malformed key-value pair

### ISSUE THREAD

**Issue by rleikis** [rickyah/ini-parser#67]
In the case of a malformed INI, such as missing a keyname, ReadFile throws an ArgumentException that is buried in Model/KeyData.cs line 19.

The way this is currently handled offers no recovery for the client calling ReadFile.  Would it not be better to detect the condition and assign the key-value pair a temporary name in the object in memory?  This would allow the client to react to the condition and possibly even repair the problem and continue.

**Comment by rickyah** [comment]
Did not forgot about this, unfortunately I been really really busy.

**Comment by rickyah** [comment]
I've been working in the first point: Provide better error messages.

You have new APIs to check errors:

* The exception `ParseException` contains a string with the line and and int with the line number that originated the error.
* `IniDataParser.HasError` returns true if `IniDataParser.Parse()`  encounter a problem
* `IniDataParser.Errors` returns a list with all the `ParsingException`s found when `IniDataParser.Parse()` is called. Will be empty if no error is found.

There are two use cases depending on the configuration option you choose:

* Library throws an exception when `IniDataParser.Parse()` fails 
The Exception is still thrown, but additionally `IniDataParser.HasError` returns `true` and 
`IniDataParser.Errors` contains one element (the ParsingException thrown).

* Library do not throws an exception when `IniParser.Parse()` fails 
In this case the Parse() method tries to process all the lines in the ini file, but returns `null`,  `IniDataParser.HasError` returns `true` and `IniDataParser.Errors` contains one ParsingException instance for each error found when parsing the file. (It will at least contain one ParsingException instance)

The bad news is: I made the changes late at night and forgot to push them and now I'm at work. You'll have to wait some more hours  :( I'm really sorry about it
