### ISSUE TITLE
IniData needs reference?

### ISSUE THREAD

**Issue by rfresh737** [rickyah/ini-parser#71]
This line:
IniData data = parser.ReadFile("Configuration.ini");
Tells me Type or Namespace 'IniData' could not be found.

How do I fix that?

I have this line at the top: using IniParser;

**Comment by rickyah** [comment]
Add a reference to the namespace:

using IniData.Model;

**Comment by quicktrick** [comment]
Hello @rickyah !
Thanks a lot for your program!  Please, add

`using IniParser;
using IniParser.Model;`

to the Wiki and to the "Getting Started" on the main page.

Regards!

Alex

**Comment by rickyah** [comment]
Done! Thanks @quicktrick!
