### ISSUE TITLE
How do I delete a complete Section?

### ISSUE THREAD

**Issue by rfresh737** [rickyah/ini-parser#72]
Can you give a c# example of how to remove an entire section from the ini file?

Thank you...

**Comment by rickyah** [comment]
iniData.Sections.RemoveSection("section_name");

**Comment by rfresh737** [comment]
My test1.ini file has this:

[1111]
1111=1111

[2222]
2222=2222

[3333]
3333=3333

[4444]
4444=4444

var parser = new FileIniDataParser();
IniData data = parser.ReadFile(@"C:\Project\test1.ini");
data.Sections.RemoveSection("3333");

But nothing changes in the file after I run this code.

**Comment by rickyah** [comment]
Changes you made only affect the IniData object in memory. If you want to persist the changes to the file, you need to overwrite the file:

````
parser.SaveFile(@"C:\Project\test1.ini", data);
````

https://github.com/rickyah/ini-parser/wiki/First-Steps#saving-the-file

**Comment by rfresh737** [comment]
OK, thanks for your help!!
