### ISSUE TITLE
Section and key names are case-sensitive, could this be configurable?

### ISSUE THREAD

**Issue by beatcracker** [rickyah/ini-parser#76]
Currently, to get content of the section\key, one has to specify section and key name in exact case as they are stored in the ini file. This is confusing, because native Windows functions [GetPriveProfileString](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724353.aspx) \ [WritePrivateProfileString](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725501.aspx) are not case-sensitive. Could this be configurable?

**UPDATE:**

I've found an old issue, that states that this is fixed

 - [Case insensitive Section and Key names #21](https://github.com/rickyah/ini-parser/issues/21)

and I've to create a derived class to modify parser behavior.

Unfortunately

 - a) I can't find nothing releveant in the [Customizing the parser](https://github.com/rickyah/ini-parser/wiki/Customizing-the-parser) wiki article (probably says more about me than about article)
 - b) I'm not a full-fledged .Net developer, just a guy trying to use your parser in the PowerShell, so chances of me writing a correct implementation are slim.

So, is there some easy way for me to achieve desired parser behavior or I'm doomed to learn C# really fast?

**Comment by beatcracker** [comment]
Currently, to get content of the section\key, one has to specify section and key name in exact case as they are stored in the ini file. This is confusing, because native Windows functions [GetPriveProfileString](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724353.aspx) \ [WritePrivateProfileString](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725501.aspx) are not case-sensitive. Could this be configurable?

**UPDATE:**

I've found an old issue, that states that this is fixed

 - [Case insensitive Section and Key names #21](https://github.com/rickyah/ini-parser/issues/21)

and I've to create a derived class to modify parser behavior.

Unfortunately

 - a) I can't find nothing releveant in the [Customizing the parser](https://github.com/rickyah/ini-parser/wiki/Customizing-the-parser) wiki article (probably says more about me than about article)
 - b) I'm not a full-fledged .Net developer, just a guy trying to use your parser in the PowerShell, so chances of me writing a correct implementation are slim.

So, is there some easy way for me to achieve desired parser behavior or I'm doomed to learn C# really fast?

**Comment by rickyah** [comment]
Hi @beatcracker 

I think that a case insensitive flag in the parser configuración would be an useful add on to the library so it is compatible with Windows native functions. I'll begin to work on it, but this week I'm really busy.

**Comment by beatcracker** [comment]
Thank you, @rickyah , it's not urgent at all, just a good thing to have.

**Comment by rickyah** [comment]
beatcracker, I've just uploaded a new PR implementing this issue: https://github.com/rickyah/ini-parser/pull/78

Please, check it out, test it if you please and don't hesitate to comment if you have any feedback.
Close the issue to follow the discussion in the PR

**Comment by beatcracker** [comment]
@rickyah, I've just built and checked new version and it works like a charm! Thank you very much.

**Comment by jamalmazrui** [comment]
Can someone please give me an example of how to implement case insensitive behavior when using the FileIniDataParser class?

**Comment by rickyah** [comment]
@jamalmazrui you can set `FileIniDataParser.Parser.Configuration.CaseInsensitive  = true`  *before parsing the file* and  you should get that behaviour 

However I recommend to not use FileIniDataParser, just read the file yourself and parse it so you can configure the parser the way you want
