### ISSUE TITLE
Values from CommentChar and CommentString are used unescaped in CommentRegex

### ISSUE THREAD

**Issue by beatcracker** [rickyah/ini-parser#77]
##### Steps to reproduce the problem:

1. Create INI file:

        [Section]
        \Backslash comment
        Key=Value

2. Set `Parser.Configuration.CommentString = '\'`

3. Try to read file using `ReadFile('.\example.ini')`

##### Expected result:

IniParser should be able to parse file and return `IniData` object.

##### What do you see instead?
    Exception calling "ReadFile" with "1" argument(s):
    "Parsing Error: Unknown file format. Couldn't parse the line: '\BackSlashComment'."

##### IniParser version:

Version `2.1.1` from [this Nuget package](https://www.nuget.org/packages/ini-parser/)

##### Mitigation:

To parse file with comments characters that need to be escaped I'm using this regex in the`CommentRegex` property: 

    ^\\(.*)

Moreover, I'm able to parse files with multiple characters for comments (including those that need to be escaped) using this regex in the`CommentRegex` property:

    ^(;|#|\\)(.*)

Note, that for multiple characters to work, they have to be enclosed in the capture group.

So here is what I propose:

1. **Bugfix**: values from `CommentChar` and `CommentString` should be escaped.
2. **Enhancement**: `CommentChar` and `CommentString` should be able to accept arrays of strings, that would be converted to regex like this:
 - Strings:
<pre>';', '#', '&#92;'</pre>
 - Resulting regex:
<pre>^(;|#|&#92;&#92;)(.*)</pre>

**Comment by rickyah** [comment]
This has been fixed in the development branch. By mistake I merged the fix with a reorganization of the tests in the commit 82ae0d05e81587f959cea19a66ac2cbb01a15729

[Here is a link to the line with the test](https://github.com/rickyah/ini-parser/commit/82ae0d05e81587f959cea19a66ac2cbb01a15729#diff-afc29b16536bd093518d401a1fca7219R180)
