### ISSUE TITLE
Quote in the Section Name

### ISSUE THREAD

**Issue by dweldy** [rickyah/ini-parser#88]
Doing something like this:
[W101    0.5" wc]
will break the parser.

Processing quotes for the key=value par within the section makes sense but may need an option to be ignored in the section name.

**Comment by dweldy** [comment]
workaround:
In the IniParserConfiguration set the value of SectionRegex to:
new Regex(@"^(\s*?)\[{1}\s*[_\""\{\}\#\+\;\*\%\(\)\=\?\&\$\,\:\/\.\-\w\d\s\\\~]+\s*](\s*?)$")

**Comment by davidgrupp** [comment]
It also fails on single quote as well

**Comment by rickyah** [comment]
I think this should be fixed by @davidgrupp's PR #93
