### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by jpenzes** [rickyah/ini-parser#90]
Hi,

if I see it correctly, the parser cannot handle now the escape characters. Is it true?
E.g.: https://en.wikipedia.org/wiki/INI_file#Escape_characters

Best regards,
János

**Comment by rickyah** [comment]
No, the parser does not currently handle escaped characters that are used for the definition of the ini file. For example you cannot escape the comment character (;) nor the equal sign as it delimites a property

**Comment by Anime4000** [comment]
all my string need do `.Replace("\n", "\\n")` before parse into INI, same with `\r` and `\t`.
I will more nice if these handle natively.

**Comment by rickyah** [comment]
Changing the actual contents the original .ini file of the user before parsing and doing it w/out warning seems like a bad idea to me
