### ISSUE TITLE
Need new NuGet release

### ISSUE THREAD

**Issue by rmunn** [rickyah/ini-parser#94]
I want to configure FileIniDataParser objects more easily using the feature added in https://github.com/rickyah/ini-parser/pull/92 (merged on September 13th), but the [latest NuGet package](https://www.nuget.org/packages/ini-parser/), v2.2.2, is from June 13th and doesn't include that feature.

I'd rather not have to build my own NuGet package; I prefer to use official packages whenever possible. Could you create a 2.2.3 release and push it to NuGet so that I can use this feature? Thanks!

**Comment by rickyah** [comment]
I'll try to push a new package today

Ricardo Amores Hernández
Twitter www.twitter.com/rickyah
LinkedIn www.linkedin.com/in/ricardoamoreshdez

**Comment by beatcracker** [comment]
Nightly Appveyor builds :wink: ?

**Comment by rickyah** [comment]
Here is the latest nuget package ;) 
https://www.nuget.org/packages/ini-parser/2.2.3
