### ISSUE TITLE
Default encoding for ini file

### ISSUE THREAD

**Issue by francescoformenti** [rickyah/ini-parser#98]
Hello,
I would like to report a small incoherence in the FileIniParser class:
the method:
`public void WriteFile(string filePath, IniData parsedData, Encoding fileEncoding = null)`
uses Encoding.ASCII if no encoding provided, but the method:
`public IniData ReadFile(string filePath)`
uses Encoding.Default.
On an Italian Windows 10 system, it causes the class to write the chars: "òàùèéì" in ASCII and, when read, these chars are wrongly loaded.
Forcing the encoding in the two methods fixes the problem, but I would advice to correct this incoherence.
Thanks for your great work!

Regards
Francesco

**Comment by rickyah** [comment]
Thanks @francescoformenti for the bug report!
I'll make ASCII the default encoding and I'll also update the mid library version as this could break compatibility
