### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by davidbollman** [rickyah/ini-parser#99]
I have an ini which isn't quite proper but for business reasons cannot change, as I suspect others do, it would be nice to allow for some accommodations for this scenario.

Specifically for me there is no header [...] sections and the comment character is non standard, in my case it's a #.  It would be a nice feature to specify to the parser a different comment character (pre Readfile), and allow for a (parent) [""]["XML"] to allow using parameters prior to a section header.

i.e. 
```csharp
var parser = new FileIniDataParser();
parser.AddCommentDelimiter('#');
IniData iniData = parser.ReadFile(iniLocation);
JobJS = iniData["JS"];  // or maybe iniData[""]["JS"];  or best option :)
```

---  sample ini file follows ----
#This is ini desc file # is comment char

#root js url
JS=http://fulljsurl.html

#file.xml, optional
XML=http://fullxml.xml

#MAC Section
BIN=BADesktop.app
BAD=fullfilename.zip
BADV=131

**Comment by Svetomech** [comment]
> in my case it's a #
But isn't changing it already possible?

**Comment by rickyah** [comment]
You can configure the parser to use a different comment character, see this page: https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior

And specifically look at IIniparserConfiguration.CommentChar

Feel free to ping me if you need further help @davidbollman

**Comment by rickyah** [comment]
@davidbollman You have an example of this configuration in the example project: https://github.com/rickyah/ini-parser/blob/development/src/INIFileParser.Example/Program.cs
